### ISSUE TITLE
Add wildcard namespace selector for `clusterLogForwarding.namespace_groups`

### ISSUE THREAD

**Issue by haasad** [appuio/component-openshift4-logging#137]
## Context

`clusterLogForwarding.namespace_groups` currently requires a list of namespaces. It would be convenient if namespaces could be selected based on naming pattern, e.g. `*-dev`. This would reduce the effort of manually keeping the namespace list up to date in the config if projects are added/removed.

## Implementation idea

- expose label selector since wildcards are not possible

**Comment by DebakelOrakel** [comment]
However, there is another interessting hook:
```
GROUP:      logging.openshift.io
KIND:       ClusterLogForwarder
VERSION:    v1

FIELD: selector <Object>

DESCRIPTION:
    Selector for logs from pods with matching labels. Only messages from pods
    with these labels are collected. If absent or empty, logs are collected
    regardless of labels.

FIELDS:
  matchLabels   <map[string]string>
    matchLabels is a map of {key,value} pairs. A single {key,value} in the
    matchLabels map is equivalent to an element of matchExpressions, whose key
    field is "key", the operator is "In", and the values array contains only
    "value". The requirements are ANDed.
```

**Comment by DebakelOrakel** [comment]
Above PR allows for configuration of features like `matchLabels` on `inputs`. 
Does that solve your issue?
