### ISSUE TITLE
Component compilation is non-deterministic with the default parameters

### ISSUE THREAD

**Issue by simu** [appuio/component-openshift4-logging#47]
The component fetches the upstream fluentd alerts from the `master` branch of https://github.com/openshift/cluster-logging-operator, cf. https://github.com/appuio/component-openshift4-logging/blob/600107cc7e823f27e9344036d0f91d2e535508f0/class/defaults.yml#L5 and https://github.com/appuio/component-openshift4-logging/blob/600107cc7e823f27e9344036d0f91d2e535508f0/class/openshift4-logging.yml#L5 By doing so, we can't generate reproducible golden test outputs, as the contents of the fluentd alerts on the master branch may change arbitrarily.

## Steps to Reproduce the Problem

  1. generate golden tests output (`make gen-golden`)
  1. observe that golden tests may fail after some time, see e.g. #46 

## Actual Behavior

Golden tests start failing if the upstream alerts are modified on the master branch

## Expected Behavior

We want deterministic compilation of components with default parameters. We should pick some stable version of the upstream repo to use in the component defaults.

**Comment by simu** [comment]
Determine which logging versions are supported on which OpenShift versions according to RedHat. If there's different supported versions per OCP version, consider implementing a map from OCP version to corresponding logging version. Otherwise, keep component updated to latest logging stack release as default (maybe check if we can do this with renovate for a Git branch).

**Comment by bastjan** [comment]
Solution for tagged releases https://github.com/renovatebot/renovate/discussions/17318

Git refs datasource has zero docs https://docs.renovatebot.com/modules/datasource/#git-refs-datasource

**Comment by bastjan** [comment]
More examples:
- https://github.com/renovatebot/renovate/discussions/16980
- https://github.com/renovatebot/renovate/discussions/8402#discussioncomment-306625
- https://github.com/renovatebot/renovate/discussions/16510#discussioncomment-3118396

**Comment by bastjan** [comment]
Digest now gets renovated #59. Looking into if there's some kinda alias possible to make nicer PR titles.

**Comment by bastjan** [comment]
Alias was possible but we now have two renovates (our self-hosted) and the offical trying to create PRs: #61 #59

**Comment by bastjan** [comment]
Have not yet found a way to exclude this repo from the GitHub Renovate App.

**Comment by simu** [comment]
We'll have to completely rethink this as the cluster-logging-operator has deleted the YAML files and moved their contents into Go sources in https://github.com/openshift/cluster-logging-operator/commit/6a46db799aa94d0c9b84ec5f4a7d2c87b2f77754
