### ISSUE TITLE
The component should manage its own alert rules

### ISSUE THREAD

**Issue by simu** [appuio/component-openshift4-logging#64]
## Context

Currently we manage and deploy alert rules for the logging stack in component openshift4-monitoring, cf. https://hub.syn.tools/openshift4-monitoring/references/parameters.html#_upstreamrules_elasticsearchoperator. This doesn't make a lot of sense, since we can't reliably select the correct version of the alert rules for the logging stack in that component, as we don't exactly know which logging stack version is deployed.

In contrast, this component always knows which logging stack version is getting installed and can therefore easily select the matching set of alert rules.

## Alternatives

Keep the alert rules management in component openshift4-monitoring

**Comment by glrf** [comment]
We should invest some time into putting some alert rule patching functionality in a library instead of duplicating it yet another time.

**Comment by simu** [comment]
> We should invest some time into putting some alert rule patching functionality in a library instead of duplicating it yet another time.

Turns out openshift4-logging already has a copy-pasted version of the rule patching, cf. https://github.com/appuio/component-openshift4-logging/blob/97d9a405ed21ae46a2ce664368f8d5fa5df4411b/component/alertrules.libsonnet#L36-L88. However, I'll still move that code to a component library offered by component openshift4-monitoring in a follow-up to the currently open PRs.
