### ISSUE TITLE
Increase pv with commodore configuration

### ISSUE THREAD

**Issue by DebakelOrakel** [appuio/component-openshift4-logging#8]
## Context
To increase elastic storage we currently need to
* increase storage in commodore config and
* increase pvc to actually increase the storage per CSI

## Alternatives
If possible it would be nice if the commodore component increased the pv as well.

**Comment by mhutter** [comment]
In either case, It would be nice to have this documented in a HowTo page

**Comment by tobru** [comment]
@DebakelOrakel @mhutter Does https://github.com/appuio/openshift4-docs/pull/151 solve your needs in this issue? It's available here: https://kb.vshn.ch/oc4/how-tos/logging/increase-elasticsearch-storage-size.html

**Comment by DebakelOrakel** [comment]
That should do it
